from enum import StrEnum


class UserErrorCode(StrEnum):
    NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_EXISTS = "USER_EMAIL_EXISTS"
    INACTIVE = "USER_INACTIVE"
    FORBIDDEN = "USER_FORBIDDEN"
    INCORRECT_PASSWORD = "USER_INCORRECT_PASSWORD"
    SAME_PASSWORD = "USER_SAME_PASSWORD"
