FROM mcr.microsoft.com/playwright:v1.62.1-noble

WORKDIR /app

COPY --from=oven/bun:1.3.14 /usr/local/bin/bun /usr/local/bin/bun
RUN ln -s /usr/local/bin/bun /usr/local/bin/bunx

COPY package.json bun.lock /app/
COPY frontend/package.json /app/frontend/

WORKDIR /app/frontend

RUN bun install --frozen-lockfile

COPY ./frontend /app/frontend

RUN bunx tsc --noEmit -p tsconfig.json

CMD ["bunx", "playwright", "test"]
